name: Test Incoming Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Run Linter and Vet
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
    env:
      SHELL: /bin/bash

    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.7

    - name: Disable default go problem matcher
      run: echo "::remove-matcher owner=go::"

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}

    - name: Run 'make vet'
      run: make vet

    - name: Install golangci-lint
      run: make install-lint

    - name: Run 'make lint'
      run: make lint

    - name: Run 'make test'
      run: make test
